### ISSUE TITLE
how to run this demo,

### ISSUE THREAD

**Issue by luoqisheng** [DmitryBespalov/ManualDependencyExample#1]
/Users/luoqisheng/works/ManualDependencyExample/ProjectC/ProjectC/ProjectC/ModelMapper.swift:10:8: Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1: /Users/luoqisheng/works/ManualDependencyExample/ProjectC/ProjectC/../../Frameworks/iphonesimulator/ObjectMapper.framework/Modules/ObjectMapper.swiftmodule/x86_64.swiftmodule

**Comment by luoqisheng** [comment]
whether it can be use to merge several framework into one,in my pure swift app.

**Comment by DmitryBespalov** [comment]
@luoqisheng Hi, this error is because the frameworks in this repository were compiled with old Xcode which had 3.0.1 Swift. Now we need to recompile the swift sub-projects with newer Xcode version so that you could use them with 3.1 Swift version.

Overall, the approach in this repo doesn't allow you to merge all the frameworks into one, it's just showing a manual approach to dependency management.

**Comment by luoqisheng** [comment]
`This came about due to many third party dependencies being converted to static libraries, and a number of dynamically linked frameworks then being dramatically decreased`,   you means third party dependencies being converted to static libraries only support ObjC?  Do you have any idea to decreased dynamically linked frameworks build by swift

**Comment by DmitryBespalov** [comment]
Hi @luoqisheng, unfortunately, I don't know any other way than removing the dependencies and implementing the required functionality by yourself.

**Comment by DmitryBespalov** [comment]
Closing, because didn't have any more updates
